In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv')

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
df1 = df[['Name','Sex','Age']][0:5]

In [7]:
df1

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                              Heikkinen, Miss Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [8]:
df2 = df[['Name','Sex','Age']][5:10]

In [9]:
df2

                                                Name     Sex   Age
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                      Palsson, Master Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [ ]:
pd.concat([df1,df2], axis = 0) # concatentate panda objects along a particular object

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                              Heikkinen, Miss Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                      Palsson, Master Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [11]:
pd.concat([df1,df2], axis = 1)

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,NaN,NaN,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,NaN,NaN,NaN
2,"Heikkinen, Miss Laina",female,26.0,NaN,NaN,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,NaN,NaN,NaN
4,"Allen, Mr. William Henry",male,35.0,NaN,NaN,NaN
5,NaN,NaN,NaN,"Moran, Mr. James",male,NaN
6,NaN,NaN,NaN,"McCarthy, Mr. Timothy J",male,54.0
7,NaN,NaN,NaN,"Palsson, Master Gosta Leonard",male,2.0
8,NaN,NaN,NaN,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
9,NaN,NaN,NaN,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

In [12]:
df2.reset_index(drop= True, inplace = True)

In [13]:
df2

                                                Name     Sex   Age
0                                   Moran, Mr. James    male   NaN
1                            McCarthy, Mr. Timothy J    male  54.0
2                      Palsson, Master Gosta Leonard    male   2.0
3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
4                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [14]:
pd.concat([df1,df2], axis = 1)

,Name,Sex,Age,Name,Sex,Age
0,"Braund, Mr. Owen Harris",male,22.0,"Moran, Mr. James",male,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,"McCarthy, Mr. Timothy J",male,54.0
2,"Heikkinen, Miss Laina",female,26.0,"Palsson, Master Gosta Leonard",male,2.0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0
4,"Allen, Mr. William Henry",male,35.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0

In [15]:
# important ..... # marge and join

In [16]:
df1 = pd.DataFrame({
    'key1' : [1,2,3,4,5,6],
    'key2' : [4,5,6,7,8,9],
    'key3' : [7,6,5,4,3,2]
})

In [18]:
df1

   key1  key2  key3
0     1     4     7
1     2     5     6
2     3     6     5
3     4     7     4
4     5     8     3
5     6     9     2

In [34]:
df2 = pd.DataFrame({
    'key1' : [1,43,5,4,6,7],
    'key4' : [32,3,2,45,65,8],
    'key5' : [12,32,43,5,46,7]
})

In [36]:
df2

   key1  key4  key5
0     1    32    12
1    43     3    32
2     5     2    43
3     4    45     5
4     6    65    46
5     7     8     7

In [ ]:
pd.merge(df1,df2, how = 'inner')

   key1  key2  key3  key4  key5
0     1     4     7    32    12
1     4     7     4    45     5
2     5     8     3     2    43
3     6     9     2    65    46

In [38]:
pd.merge(df1,df2, how = 'left')

   key1  key2  key3  key4  key5
0     1     4     7  32.0  12.0
1     2     5     6   NaN   NaN
2     3     6     5   NaN   NaN
3     4     7     4  45.0   5.0
4     5     8     3   2.0  43.0
5     6     9     2  65.0  46.0

In [39]:
pd.merge(df1,df2, how = 'right')

   key1  key2  key3  key4  key5
0     1   4.0   7.0    32    12
1    43   NaN   NaN     3    32
2     5   8.0   3.0     2    43
3     4   7.0   4.0    45     5
4     6   9.0   2.0    65    46
5     7   NaN   NaN     8     7

In [42]:
pd.merge(df1,df2, how = 'outer') # all the keys from both the dataframe

   key1  key2  key3  key4  key5
0     1   4.0   7.0  32.0  12.0
1     2   5.0   6.0   NaN   NaN
2     3   6.0   5.0   NaN   NaN
3     4   7.0   4.0  45.0   5.0
4     5   8.0   3.0   2.0  43.0
5     6   9.0   2.0  65.0  46.0
6     7   NaN   NaN   8.0   7.0
7    43   NaN   NaN   3.0  32.0

In [43]:
df1

   key1  key2  key3
0     1     4     7
1     2     5     6
2     3     6     5
3     4     7     4
4     5     8     3
5     6     9     2

In [44]:
df2

   key1  key4  key5
0     1    32    12
1    43     3    32
2     5     2    43
3     4    45     5
4     6    65    46
5     7     8     7

In [ ]:
pd.merge(df1, df2, how = 'cross') # combination of df1 and df2

    key1_x  key2  key3  key1_y  key4  key5
0        1     4     7       1    32    12
1        1     4     7      43     3    32
2        1     4     7       5     2    43
3        1     4     7       4    45     5
4        1     4     7       6    65    46
5        1     4     7       7     8     7
6        2     5     6       1    32    12
7        2     5     6      43     3    32
8        2     5     6       5     2    43
9        2     5     6       4    45     5
10       2     5     6       6    65    46
11       2     5     6       7     8     7
12       3     6     5       1    32    12
13       3     6     5      43     3    32
14       3     6     5       5     2    43
15       3     6     5       4    45     5
16       3     6     5       6    65    46
17       3     6     5       7     8     7
18       4     7     4       1    32    12
19       4     7     4      43     3    32
20       4     7     4       5     2    43
21       4     7     4       4    45     5
22       4     7     4       6    65    46
23       4     7     4       7     8     7
24       5     8     3       1    32    12
25       5     8     3      43     3    32
26       5     8     3       5     2    43
27       5     8     3       4    45     5
28       5     8     3       6    65    46
29       5     8     3       7     8     7
30       6     9     2       1    32    12
31       6     9     2      43     3    32
32       6     9     2       5     2    43
33       6     9     2       4    45     5
34       6     9     2       6    65    46
35       6     9     2       7     8     7

In [46]:
pd.merge(df1, df2, how = 'left', left_on='key2', right_on='key4')

   key1_x  key2  key3  key1_y  key4  key5
0       1     4     7     NaN   NaN   NaN
1       2     5     6     NaN   NaN   NaN
2       3     6     5     NaN   NaN   NaN
3       4     7     4     NaN   NaN   NaN
4       5     8     3     7.0   8.0   7.0
5       6     9     2     NaN   NaN   NaN