In [5]:
# pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
# built on top of the python programing language

#2008, Mckinney
#very well with structured data

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('services.csv') # Read a coma-sepaated value (csv) file into DataFrame.

In [4]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [25]:
df = pd.read_csv('services.csv', header = None) # internal interger indexes are provided by pandas
df

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
1,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
2,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
3,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
4,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
5,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
6,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
7,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
8,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
9,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
10,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
11,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
12,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
13,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
14,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
15,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
16,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
17,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
18,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
19,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
20,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
21,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
22,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
23,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [ ]:
df = pd.read_csv('services.csv',skiprows = 2) #internal integer indexs are provide by pandas
df

,2,2.1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligible people age 55 or over who meet certain income qualifications.,"Age 55 or over, county resident and willing and able to work. Income requirements vary according to program",Unnamed: 9,...,Unnamed: 12,"EMPLOYMENT/TRAINING SERVICES, Job Development, Job Information/Placement/Referral, Job Training, Job Training Formats, Job Search/Placement, Older Adults",Unnamed: 14,Second Career Employment Program,Unnamed: 16,San Mateo County,active,Varies.,Unnamed: 20,Unnamed: 21
0,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
1,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
2,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
3,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
4,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
5,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
6,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
7,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
8,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
10,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
12,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
13,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
14,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
15,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
16,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
17,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
18,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
19,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
20,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [29]:
df = pd.read_csv('services.csv', usecols = ['program_id','application_process'])
df

    program_id                                application_process
0          NaN                         Walk in or apply by phone.
1          NaN                 Apply by phone for an appointment.
2          NaN        Phone for information (403-4300 Ext. 4322).
3          NaN                                    Apply by phone.
4          NaN                             Phone for information.
5          NaN  Walk in or apply by phone for membership appli...
6          NaN  Apply by phone or be referred by a doctor, soc...
7          NaN                                    Apply by phone.
8          NaN  Walk in. Proof of residency in California requ...
9          NaN  Walk in. Proof of California residency to rece...
10         NaN  Walk in. Proof of California residency require...
11         NaN  Walk in or apply by phone, email or webpage re...
12         NaN  Walk in. Proof of California residency require...
13         NaN  Call for appointment. Referral from human serv...
14         NaN          Walk in or through other agency referral.
15         NaN  Walk in. Written application, identification r...
16         NaN                              Call for information.
17         NaN  Call for screening appointment. Medical visits...
18         NaN     Call for screening appointment (650-347-3648).
19         NaN                                           Walk in.
20         NaN                    By phone during business hours.
21         NaN                  Walk in or apply by phone or mail
22         NaN                  Walk in or apply by phone or mail

In [30]:
# data structure >> series  and dataframe
#series >> 1 dimenstion in nature
#dataframe >> 2 dimenstion in nature , multiple series constitutes to form a dataform

In [31]:
type(df)

pandas.DataFrame

In [32]:
df.application_process

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str

In [33]:
df['application_process']

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str

In [34]:
l = [1,2,3,4]
s = pd.Series(l)
s

0    1
1    2
2    3
3    4
dtype: int64

In [35]:
type(s)

pandas.Series

In [36]:
s[0]

np.int64(1)

In [37]:
s[1]

np.int64(2)

In [38]:
s[2:4]

2    3
3    4
dtype: int64

In [39]:
s[2:]

2    3
3    4
dtype: int64

In [5]:
d = pd.Series([100,200,300],['Rana','Vivek','Raghu'])
d

Rana     100
Vivek    200
Raghu    300
dtype: int64

In [41]:
type(d)

pandas.Series

In [6]:
d['Raghu']

np.int64(300)

In [7]:
d.index

Index(['Rana', 'Vivek', 'Raghu'], dtype='str')

In [8]:
d['Rana':'Raghu']

Rana     100
Vivek    200
Raghu    300
dtype: int64

In [47]:
d.reset_index(drop=True)

0    100
1    200
2    300
dtype: int64

In [9]:
d.reset_index()

   index    0
0   Rana  100
1  Vivek  200
2  Raghu  300

In [10]:
pd.DataFrame(d)

         0
Rana   100
Vivek  200
Raghu  300

In [52]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [53]:
df.shape

(23, 22)

In [54]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='str')

In [55]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [56]:
df.head(4)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN

In [57]:
df.head(7)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN

In [59]:
df.tail(5)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [ ]:
df.sample(3) # sample -> take random from csv file data

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       23 non-null     int64
 1   location_id              23 non-null     int64
 2   program_id               0 non-null      float64
 3   accepted_payments        1 non-null      str
 4   alternate_name           1 non-null      str
 5   application_process      23 non-null     str
 6   audience                 14 non-null     str
 7   description              23 non-null     str
 8   eligibility              17 non-null     str
 9   email                    1 non-null      str
 10  fees                     21 non-null     str
 11  funding_sources          21 non-null     str
 12  interpretation_services  1 non-null      str
 13  keywords                 21 non-null     str
 14  languages                1 non-null      str
 15  name                     23 non-null     str
 16  required_documents       1 non-null      str
 17  service_areas            21 non-null     str
 18  status                   23 non-null     str
 19  wait_time                19 non-null     str
 20  website                  2 non-null      str
 21  taxonomy_ids             1 non-null      str
dtypes: float64(1), int64(2), str(19)
memory usage: 4.1 KB

In [62]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments              str
alternate_name                 str
application_process            str
audience                       str
description                    str
eligibility                    str
email                          str
fees                           str
funding_sources                str
interpretation_services        str
keywords                       str
languages                      str
name                           str
required_documents             str
service_areas                  str
status                         str
wait_time                      str
website                        str
taxonomy_ids                   str
dtype: object

In [63]:
df['id']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
Name: id, dtype: int64

In [64]:
df['application_process']

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str

In [65]:
type(df['application_process'])

pandas.Series

In [67]:
list[df['application_process']]

list[0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical visits...
18       Call for screening appointment (650-347-3648).
19                                             Walk in.
20                      By phone during business hours.
21                    Walk in or apply by phone or mail
22                    Walk in or apply by phone or mail
Name: application_process, dtype: str]

In [11]:
#series to dataframe

s = pd.Series([2,3,4], index = [100,'Ajay',2])
s

100     2
Ajay    3
2       4
dtype: int64

In [12]:
d = pd.DataFrame(s)
d

      0
100   2
Ajay  3
2     4

In [13]:
d['new column'] = 'Raj'
d

      0 new column
100   2        Raj
Ajay  3        Raj
2     4        Raj

In [14]:
d['new column']

100     Raj
Ajay    Raj
2       Raj
Name: new column, dtype: str

In [15]:
d['new column']

100     Raj
Ajay    Raj
2       Raj
Name: new column, dtype: str

In [16]:
d.columns = ['id','name']

In [17]:
d

      id name
100    2  Raj
Ajay   3  Raj
2      4  Raj

In [18]:
d.reset_index()

  index  id name
0   100   2  Raj
1  Ajay   3  Raj
2     2   4  Raj

In [19]:
d.reset_index(drop=True)

   id name
0   2  Raj
1   3  Raj
2   4  Raj

In [20]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='str')

In [21]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [22]:
df.id

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
Name: id, dtype: int64

In [23]:
df.required_documents

0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
5                                          NaN
6                                          NaN
7                                          NaN
8                                          NaN
9                                          NaN
10                                         NaN
11                                         NaN
12                                         NaN
13                                         NaN
14                                         NaN
15                                         NaN
16                                         NaN
17                                         NaN
18                                         NaN
19                                         NaN
20                                         NaN
21    Government-issued picture identification
22                                         NaN
Name: required_documents, dtype: str

In [26]:
df_subset = df[['name','languages','status']]
df_subset

                                    name languages    status
0        Fair Oaks Adult Activity Center       NaN    active
1       Second Career Employment Program       NaN    active
2                 Senior Peer Counseling       NaN    active
3               Family Visitation Center       NaN    active
4      Economic Self-Sufficiency Program       NaN    active
5   Little House Recreational Activities       NaN    active
6       Rosener House Adult Day Services       NaN    active
7         Meals on Wheels - South County       NaN    active
8                       Fair Oaks Branch       NaN    active
9                           Main Library       NaN    active
10                       Schaberg Branch       NaN    active
11                          Project Read       NaN    active
12                 Redwood Shores Branch       NaN    active
13                    Redwood City Corps       NaN    active
14           Adult Rehabilitation Center       NaN    active
15                       Sunnyvale Corps       NaN    active
16     South San Francisco Citadel Corps       NaN    active
17                         Project Smile       NaN    active
18         San Mateo Free Medical Clinic       NaN    active
19             Service with blank fields       NaN   defunct
20       Service for Admin Test Location       NaN  inactive
21                       Passport Photos   Spanish    active
22                  Example Service Name       NaN    active

In [30]:
pd.read_excel("LUSID Excel - Setting up your market data.xlsx")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,Getting Started tutorials,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,Knowledge Base articles,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,or Contact us,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,LUSID accepts datetimes in any recognised Exce...,NaN,NaN,"LUSID also accepts UTC, UTS offsets and cutlabels",NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,Excel formats to show datetime,NaN,NaN,Additional formats,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,Enter the date to convert,2019-04-10 00:00:00,NaN,Standard UTC timestamp:,"""YYYY-MM-DDTHH:MM:SS.00Z""","Where Z indicates Zulu time (UTC+0), and is eq..."
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,This date has no time component,2019-04-10 00:00:00,NaN,Convert date into a string,2019-04-10T 13:30:45.55Z,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Specify time component,13:30:45.550000,NaN,UTC offset (not recognised as an excel date),2019-04-10T13:30:45+04:00,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,Add to your date and display the complete date...,2019-04-10 13:30:45.550000,NaN,Cutlabel,2019-04-10NSingaporeClose,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,Although the date can still appears without time,2019-04-10 13:30:45.550000,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,Add an hour to your datetime,2019-04-10 14:30:45.550000,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,Subtract a minute from your datetime,2019-04-10 14:29:45.550000,NaN,NaN,NaN,NaN

In [28]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [29]:
import pandas as pd

df = pd.read_excel("LUSID Excel - Setting up your market data.xlsx")

df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df1 = pd.read_excel("LUSID Excel - Setting up your market data.xlsx")
df1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Datetimes in LUSID,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,This sheet allows you to format datetimes for...,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,If you have any questions please visit our:,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,Getting Started tutorials,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,Knowledge Base articles,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,or Contact us,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,LUSID accepts datetimes in any recognised Exce...,NaN,NaN,"LUSID also accepts UTC, UTS offsets and cutlabels",NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,Excel formats to show datetime,NaN,NaN,Additional formats,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,Enter the date to convert,2019-04-10 00:00:00,NaN,Standard UTC timestamp:,"""YYYY-MM-DDTHH:MM:SS.00Z""","Where Z indicates Zulu time (UTC+0), and is eq..."
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,This date has no time component,2019-04-10 00:00:00,NaN,Convert date into a string,2019-04-10T 13:30:45.55Z,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Specify time component,13:30:45.550000,NaN,UTC offset (not recognised as an excel date),2019-04-10T13:30:45+04:00,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,Add to your date and display the complete date...,2019-04-10 13:30:45.550000,NaN,Cutlabel,2019-04-10NSingaporeClose,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,Although the date can still appears without time,2019-04-10 13:30:45.550000,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,Add an hour to your datetime,2019-04-10 14:30:45.550000,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,Subtract a minute from your datetime,2019-04-10 14:29:45.550000,NaN,NaN,NaN,NaN

In [32]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='str')

In [33]:
df1.shape

(28, 10)

In [35]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Unnamed: 1  0 non-null      float64
 2   Unnamed: 2  0 non-null      float64
 3   Unnamed: 3  3 non-null      str
 4   Unnamed: 4  12 non-null     str
 5   Unnamed: 5  7 non-null      object
 6   Unnamed: 6  0 non-null      float64
 7   Unnamed: 7  6 non-null      str
 8   Unnamed: 8  4 non-null      str
 9   Unnamed: 9  1 non-null      str
dtypes: float64(4), object(1), str(5)
memory usage: 2.3+ KB

In [37]:
pd.read_csv('taxonomy.csv')

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [40]:
%pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp314-cp314-macosx_10_15_universal2.whl.metadata (3.5 kB)
Downloading lxml-6.1.1-cp314-cp314-macosx_10_15_universal2.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 497.2 kB/s  0:00:16m0:00:0100:01
Installing collected packages: lxml
Successfully installed lxml-6.1.1

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [10]:
import lxml

In [ ]:
import pandas as pd
pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")
#---------------#
# this site not working my system showing 403 error. So, i download html file.

In [38]:
import pandas as pd
import os

html_files = [f for f in os.listdir() if f.endswith(".html")]

print(html_files)

tables = pd.read_html(html_files[0])

df = tables[0]

print(df.head())

['2014-15 NBA .html']
                    0        1  2  3
0      Boston Celtics  (56-26)  F  $
1     New York Knicks  (53-29)  F  $
2     Toronto Raptors  (46-36)  F  $
3  Philadelphia 76ers  (45-37)  F  $
4       Brooklyn Nets  (20-62)  F  $

In [41]:
url_df = pd.read_html('2014-15 NBA .html')

In [42]:
type(url_df)

list

In [43]:
df4 = url_df[0]

In [44]:
df4

                    0        1  2  3
0      Boston Celtics  (56-26)  F  $
1     New York Knicks  (53-29)  F  $
2     Toronto Raptors  (46-36)  F  $
3  Philadelphia 76ers  (45-37)  F  $
4       Brooklyn Nets  (20-62)  F  $

In [45]:
df4.shape

(5, 4)

In [46]:
df4.head()

                    0        1  2  3
0      Boston Celtics  (56-26)  F  $
1     New York Knicks  (53-29)  F  $
2     Toronto Raptors  (46-36)  F  $
3  Philadelphia 76ers  (45-37)  F  $
4       Brooklyn Nets  (20-62)  F  $

In [47]:
df4.info

<bound method DataFrame.info of                     0        1  2  3
0      Boston Celtics  (56-26)  F  $
1     New York Knicks  (53-29)  F  $
2     Toronto Raptors  (46-36)  F  $
3  Philadelphia 76ers  (45-37)  F  $
4       Brooklyn Nets  (20-62)  F  $>

In [48]:
df4.columns

Index([0, 1, 2, 3], dtype='int64')

In [49]:
df4.to_csv("player.csv", index = False)

In [51]:
url = "https://api.github.com/users"
pd.read_json(url)

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,user_view_type,site_admin
0,mojombo,1,MDQ6VXNlcjE=,https://avatars.githubusercontent.com/u/1?v=4,,https://api.github.com/users/mojombo,https://github.com/mojombo,https://api.github.com/users/mojombo/followers,https://api.github.com/users/mojombo/following...,https://api.github.com/users/mojombo/gists{/gi...,https://api.github.com/users/mojombo/starred{/...,https://api.github.com/users/mojombo/subscript...,https://api.github.com/users/mojombo/orgs,https://api.github.com/users/mojombo/repos,https://api.github.com/users/mojombo/events{/p...,https://api.github.com/users/mojombo/received_...,User,public,False
1,defunkt,2,MDQ6VXNlcjI=,https://avatars.githubusercontent.com/u/2?v=4,,https://api.github.com/users/defunkt,https://github.com/defunkt,https://api.github.com/users/defunkt/followers,https://api.github.com/users/defunkt/following...,https://api.github.com/users/defunkt/gists{/gi...,https://api.github.com/users/defunkt/starred{/...,https://api.github.com/users/defunkt/subscript...,https://api.github.com/users/defunkt/orgs,https://api.github.com/users/defunkt/repos,https://api.github.com/users/defunkt/events{/p...,https://api.github.com/users/defunkt/received_...,User,public,False
2,pjhyett,3,MDQ6VXNlcjM=,https://avatars.githubusercontent.com/u/3?v=4,,https://api.github.com/users/pjhyett,https://github.com/pjhyett,https://api.github.com/users/pjhyett/followers,https://api.github.com/users/pjhyett/following...,https://api.github.com/users/pjhyett/gists{/gi...,https://api.github.com/users/pjhyett/starred{/...,https://api.github.com/users/pjhyett/subscript...,https://api.github.com/users/pjhyett/orgs,https://api.github.com/users/pjhyett/repos,https://api.github.com/users/pjhyett/events{/p...,https://api.github.com/users/pjhyett/received_...,User,public,False
3,wycats,4,MDQ6VXNlcjQ=,https://avatars.githubusercontent.com/u/4?v=4,,https://api.github.com/users/wycats,https://github.com/wycats,https://api.github.com/users/wycats/followers,https://api.github.com/users/wycats/following{...,https://api.github.com/users/wycats/gists{/gis...,https://api.github.com/users/wycats/starred{/o...,https://api.github.com/users/wycats/subscriptions,https://api.github.com/users/wycats/orgs,https://api.github.com/users/wycats/repos,https://api.github.com/users/wycats/events{/pr...,https://api.github.com/users/wycats/received_e...,User,public,False
4,ezmobius,5,MDQ6VXNlcjU=,https://avatars.githubusercontent.com/u/5?v=4,,https://api.github.com/users/ezmobius,https://github.com/ezmobius,https://api.github.com/users/ezmobius/followers,https://api.github.com/users/ezmobius/followin...,https://api.github.com/users/ezmobius/gists{/g...,https://api.github.com/users/ezmobius/starred{...,https://api.github.com/users/ezmobius/subscrip...,https://api.github.com/users/ezmobius/orgs,https://api.github.com/users/ezmobius/repos,https://api.github.com/users/ezmobius/events{/...,https://api.github.com/users/ezmobius/received...,User,public,False
5,ivey,6,MDQ6VXNlcjY=,https://avatars.githubusercontent.com/u/6?v=4,,https://api.github.com/users/ivey,https://github.com/ivey,https://api.github.com/users/ivey/followers,https://api.github.com/users/ivey/following{/o...,https://api.github.com/users/ivey/gists{/gist_id},https://api.github.com/users/ivey/starred{/own...,https://api.github.com/users/ivey/subscriptions,https://api.github.com/users/ivey/orgs,https://api.github.com/users/ivey/repos,https://api.github.com/users/ivey/events{/priv...,https://api.github.com/users/ivey/received_events,User,public,False
6,evanphx,7,MDQ6VXNlcjc=,https://avatars.githubusercontent.com/u/7?v=4,,https://api.github.com/users/evanphx,https://github.com/evanphx,https://api.github.com/users/evanphx/followers,https://api.github.com/users/evanphx/following...,https://api.github.com/users/evanphx/gists{/gi...,https://api.github.com/users/evanphx/starred{/...,https://api.github.com/users/evanphx/subscript...,https://api.github.com/users/evanphx/orgs,https://api.github.com/users/evanphx/repos,https://api.github.com/users/evanphx/events{/p...,https://api.github.com/users/evanphx/received_...,User,public,False
7,vanpelt,17,MDQ6VXNlcjE3,https://avatars.githubusercontent.com/u/17?v=4,,https://api.github.com/users/vanpelt,https://github.com/vanpelt,https://api.github.com/users/vanpelt/followers,https://api.github.com/users/vanpelt/following...,https://api.github.com/users/vanpelt/gists{/gi...,https://api.github.com/users/vanpelt/starred{/...,https://api.github.com/users/vanpelt/subscript...,https://api.github.com/users/vanpelt/orgs,https://api.github.com/users/vanpelt/repos,https://api.github.com/users/vanpelt/events{/p...,https://api.github.com/users/vanpelt/received_...,User,public,False
8,wayneeseguin,18,MDQ6VXNlcjE4,https://avatars.githubusercontent.com/u/18?v=4,,https://api.github.com/users/wayneeseguin,https://github.com/wayneeseguin,https://api.github.com/users/wayneeseguin/foll...,https://api.github.com/users/wayneeseguin/foll...,https://api.github.com/users/wayneeseguin/gist...,https://api.github.com/users/wayneeseguin/star...,https://api.github.com/users/wayneeseguin/subs...,https://api.github.com/users/wayneeseguin/orgs,https://api.github.com/users/wayneeseguin/repos,https://api.github.com/users/wayneeseguin/even...,https://api.github.com/users/wayneeseguin/rece...,User,public,False
9,brynary,19,MDQ6VXNlcjE5,https://avatars.githubusercontent.com/u/19?v=4,,https://api.github.com/users/brynary,https://github.com/brynary,https://api.github.com/users/brynary/followers,https://api.github.com/users/brynary/following...,https://api.github.com/users/brynary/gists{/gi...,https://api.github.com/users/brynary/starred{/...,https://api.github.com/users/brynary/subscript...,https://api.github.com/users/brynary/orgs,https://api.github.com/users/brynary/repos,https://api.github.com/users/brynary/events{/p...,https://api.github.com/users/brynary/received_...,User,public,False
10,kevinclark,20,MDQ6VXNlcjIw,https://avatars.githubusercontent.com/u/20?v=4,,https://api.github.com/users/kevinclark,https://github.com/kevinclark,https://api.github.com/users/kevinclark/followers,https://api.github.com/users/kevinclark/follow...,https://api.github.com/users/kevinclark/gists{...,https://api.github.com/users/kevinclark/starre...,https://api.github.com/users/kevinclark/subscr...,https://api.github.com/users/kevinclark/orgs,https://api.github.com/users/kevinclark/repos,https://api.github.com/users/kevinclark/events...,https://api.github.com/users/kevinclark/receiv...,User,public,False
11,technoweenie,21,MDQ6VXNlcjIx,https://avatars.githubusercontent.com/u/21?v=4,,https://api.github.com/users/technoweenie,https://github.com/technoweenie,https://api.github.com/users/technoweenie/foll...,https://api.github.com/users/technoweenie/foll...,https://api.github.com/users/technoweenie/gist...,https://api.github.com/users/technoweenie/star...,https://api.github.com/users/technoweenie/subs...,https://api.github.com/users/technoweenie/orgs,https://api.github.com/users/technoweenie/repos,https://api.github.com/users/technoweenie/even...,https://api.github.com/users/technoweenie/rece...,User,public,False
12,macournoyer,22,MDQ6VXNlcjIy,https://avatars.githubusercontent.com/u/22?v=4,,https://api.github.com/users/macournoyer,https://github.com/macournoyer,https://api.github.com/users/macournoyer/follo...,https://api.github.com/users/macournoyer/follo...,https://api.github.com/users/macournoyer/gists...,https://api.github.com/users/macournoyer/starr...,https://api.github.com/users/macournoyer/subsc...,https://api.github.com/users/macournoyer/orgs,https://api.github.com/users/macournoyer/repos,https://api.github.com/users/macournoyer/event...,https://api.github.com/users/macournoyer/recei...,User,public,False
13,takeo,23,MDQ6VXNlcjIz,https://avatars.githubusercontent.com/u/23?v=4,,https://api.github.com/users/takeo,https://github.com/takeo,https://api.github.com/users/takeo/followers,https://api.github.com/users/takeo/following{/...,https://api.github.com/users/takeo/gists{/gist...,https://api.github.com/users/takeo/starred{/ow...,https://api.github.com/users/takeo/subscriptions,https://api.github.com/users/takeo/orgs,https://api.github.com/users/takeo/repos,https://api.github.com/users/takeo/events{/pri...,https://api.github.com/users/takeo/received_ev...,User,public,False
14,caged,25,MDQ6VXNlcjI1,https://avatars.githubusercontent.com/u/25?v=4,,https://api.github.com/users/caged,https://github.com/caged,https://api.github.com/users/caged/followers,https://api.github.com/users/caged/following{/...,https://api.github.com/users/caged/gists{/gist...,https://api.github.com/users/caged/starred{/ow...,https://api.github.com/users/caged/subscriptions,https://api.github.com/users/caged/orgs,https://api.github.com/users/caged/repos,https://api.github.com/users/caged/events{/pri...,https://api.github.com/users/caged/received_ev...,User,public,False
15,topfunky,26,MDQ6VXNlcjI2,https://avatars.githubusercontent.com/u/26?v=4,,https://api.github.com/users/topfunky,https://github.com/topfunky,https://api.github.com/users/topfunky/followers,https://api.github.com/users/topfunky/followin...,https://api.github.com/users/topfunky/gists{/g...,https://api.github.com/users/topfunky/starred{...,https://api.github.com/users/topfunky/subscrip...,https://api.github.com/users/topfunky/orgs,https://api.github.com/users/topfunky/repos,https://api.github.com/users/topfunky/events{/...,https://api.github.com/users/topfunky/received...,User,public,False
16,anotherjesse,27,MDQ6VXNlcjI3,https://avatars.githubusercontent.com/u/27?v=4,,https://api.github.com/users/anotherjesse,https://github.com/anotherjesse,https://api.github.com/users/anotherjesse/foll...,https://api.github.com/users/anotherjesse/foll...,https://api.github.com/users/anotherjesse/gist...,https://api.github.com/users/anotherjesse/star...,https://api.github.com/users/anotherjesse/subs...,https://api.github.com/users/anotherjesse/orgs,https://api.github.com/users/anotherjesse/repos,https://api.github.com/users/anotherjesse/even...,https://api.github.com/users/anotherjesse/rece...,User,public,False
17,roland,28,MDQ6VXNlcjI4,https://avatars.githubusercontent.com/u/28?v=4,,https://api.github.com/users/roland,https://github.com/roland,https://api.github.com/users/roland/followers,https://api.github.com/users/roland/following{...,https://api.github.com/users/roland/gists{/gis...,https://api.github.com/users/roland/starred{/o...,https://api.github.com/users/roland/subscriptions,https://api.github.com/users/roland/orgs,https://api.github.com/users/roland/repos,https://api.github.com/users/roland/events{/pr...,https://api.github.com/users/roland/received_e...,User,public,False
18,lukas,29,MDQ6VXNlcjI5,https://avatars.githubusercontent.com/u/29?v=4,,https://api.github.com/users/lukas,https://github.com/lukas,https://api.github.com/users/lukas/followers,https://api.github.com/users/lukas/following{/...,https://api.github.com/users/lukas/gists{/gist...,https://api.github.com/users/lukas/starred{/ow...,https://api.github.com/users/lukas/subscriptions,https://api.github.com/users/lukas/orgs,https://api.github.com/users/lukas/repos,https://api.github.com/users/lukas/events{/pri...,https://api.github.com/users/lukas/received_ev...,User,public,False
19,fanvsfan,30,MDQ6VXNlcjMw,https://avatars.githubusercontent.com/u/30?v=4,,https://api.github.com/users/fanvsfan,https://github.com/fanvsfan,https://api.github.com/users/fanvsfan/followers,https://api.github.com/users/fanvsfan/followin...,https://api.github.com/users/fanvsfan/gists{/g...,https://api.github.com/users/fanvsfan/starred{...,https://api.github.com/users/fanvsfan/subscrip...,https://api.github.com/users/fanvsfan/orgs,https://api.github.com/users/fanvsfan/repos,https://api.github.com/users/fanvsfan/events{/...,https://api.github.com/users/fanvsfan/received...,User,public,False
20,tomtt,31,MDQ6VXNlcjMx,https://avatars.githubusercontent.com/u/31?v=4,,https://api.github.com/users/tomtt,https://github.com/tomtt,https://api.github.com/users/tomtt/followers,https://api.github.com/users/tomtt/following{/...,https://api.github.com/users/tomtt/gists{/gist...,https://api.github.com/users/tomtt/starred{/ow...,https://api.github.com/users/tomtt/subscriptions,https://api.github.com/users/tomtt/orgs,https://api.github.com/users/tomtt/repos,https://api.github.com/users/tomtt/events{/pri...,https://api.github.com/users/tomtt/received_ev...,User,public,False
21,railsjitsu,32,MDQ6VXNlcjMy,https://avatars.githubusercontent.com/u/32?v=4,,https://api.github.com/users/railsjitsu,https://github.com/railsjitsu,https://api.github.com/users/railsjitsu/followers,https://api.github.com/users/railsjitsu/follow...,https://api.github.com/users/railsjitsu/gists{...,https://api.github.com/users/railsjitsu/starre...,https://api.github.com/users/railsjitsu/subscr...,https://api.github.com/users/railsjitsu/orgs,https://api.github.com/users/railsjitsu/repos,https://api.github.com/users/railsjitsu/events...,https://api.github.com/users/railsjitsu/receiv...,User,public,False
22,nitay,34,MDQ6VXNlcjM0,https://avatars.githubusercontent.com/u/34?v=4,,https://api.github.com/users/nitay,https://github.com/nitay,https://api.github.com/users/nitay/followers,https://api.github.com/users/nitay/following{/...,https://api.github.com/users/nitay/gists{/gist...,https://api.github.com/users/nitay/starred{/ow...,https://api.github.com/users/nitay/subscriptions,https://api.github.com/users/nitay/orgs,https://api.github.com/users/nitay/repos,https://api.github.com/users/nitay/events{/pri...,https://api.github.com/users/nitay/received_ev...,User,public,False
23,kevwil,35,MDQ6VXNlcjM1,https://avatars.githubusercontent.com/u/35?v=4,,https://api.github.com/users/kevwil,https://github.com/kevwil,https://api.github.com/users/kevwil/followers,https://api.github.com/users/kevwil/following{...,https://api.github.com/users/kevwil/gists{/gis...,https://api.github.com/users/kevwil/starred{/o...,https://api.github.com/users/kevwil/subscriptions,https://api.github.com/users/kevwil/orgs,https://api.github.com/users/kevwil/repos,https://api.github.com/users/kevwil/events{/pr...,https://api.github.com/users/kevwil/received_e...,User,public,False
24,KirinDave,36,MDQ6VXNlcjM2,https://avatars.githubusercontent.com/u/36?v=4,,https://api.github.com/users/KirinDave,https://github.com/KirinDave,https://api.github.com/users/KirinDave/followers,https://api.github.com/users/KirinDave/followi...,https://api.github.com/users/KirinDave/gists{/...,https://api.github.com/users/KirinDave/starred...,https://api.github.com/users/KirinDave/subscri...,https://api.github.com/users/KirinDave/orgs,https://api.github.com/users/KirinDave/repos,https://api.github.com/users/KirinDave/events{...,https://api.github.com/users/KirinDave/receive...,User,public,False
25,jamesgolick,37,MDQ6VXNlcjM3,https://avatars.githubusercontent.com/u/37?v=4,,https://api.github.com/users/jamesgolick,https://github.com/jamesgolick,https://api.github.com/users/jamesgolick/follo...,https://api.github.com/users/jamesgolick/follo...,https://api.github.com/users/jamesgolick/gists...,https://api.github.com/users/jamesgolick/starr...,https://api.github.com/users/jamesgolick/subsc...,https://api.github.com/users/jamesgolick/orgs,https://api.github.com/users/jamesgolick/repos,https://api.github.com/users/jamesgolick/event...,https://api.github.com/users/jamesgolick/recei...,User,public,False
26,atmos,38,MDQ6VXNlcjM4,https://avatars.githubusercontent.com/u/38?v=4,,https://api.github.com/users/atmos,https://github.com/atmos,https://api.github.com/users/atmos/followers,https://api.github.com/users/atmos/following{/...,https://api.github.com/users/atmos/gists{/gist...,https://api.github.com/users/atmos/starred{/ow...,https://api.github.com/users/atmos/subscriptions,https://api.github.com/users/atmos/orgs,https://api.github.com/users/atmos/repos,https://api.github.com/users/atmos/events{/pri...,https://api.github.com/users/atmos/received_ev...,User,public,False
27,sethfitz,45,MDQ6VXNlcjQ1,https://avatars.githubusercontent.com/u/45?v=4,,https://api.github.com/users/sethfitz,https://github.com/sethfitz,https://api.github.com/users/sethfitz/followers,https://api.github.com/users/sethfitz/followin...,https://api.github.com/users/sethfitz/gists{/g...,https://api.github.com/users/sethfitz/starred{...,https://api.github.com/users/sethfitz/subscrip...,https://api.github.com/users/sethfitz/orgs,https://api.github.com/users/sethfitz/repos,https://api.github.com/users/sethfitz/events{/...,https://api.github.com/users/sethfitz/received...,User,public,False
28,bmizerany,46,MDQ6VXNlcjQ2,https://avatars.githubusercontent.com/u/46?v=4,,https://api.github.com/users/bmizerany,https://github.com/bmizerany,https://api.github.com/users/bmizerany/followers,https://api.github.com/users/bmizerany/followi...,https://api.github.com/users/bmizerany/gists{/...,https://api.github.com/users/bmizerany/starred...,https://api.github.com/users/bmizerany/subscri...,https://api.github.com/users/bmizerany/orgs,https://api.github.com/users/bmizerany/repos,https://api.github.com/users/bmizerany/events{...,https://api.github.com/users/bmizerany/receive...,User,public,False
29,jnewland,47,MDQ6VXNlcjQ3,https://avatars.githubusercontent.com/u/47?v=4,,https://api.github.com/users/jnewland,https://github.com/jnewland,https://api.github.com/users/jnewland/followers,https://api.github.com/users/jnewland/followin...,https://api.github.com/users/jnewland/gists{/g...,https://api.github.com/users/jnewland/starred{...,https://api.github.com/users/jnewland/subscrip...,https://api.github.com/users/jnewland/orgs,https://api.github.com/users/jnewland/repos,https://api.github.com/users/jnewland/events{/...,https://api.github.com/users/jnewland/received...,User,public,False

In [52]:
import requests
data = requests.get(url)

In [53]:
data

In [54]:
df6 = data.json()

In [55]:
df6

[{'login': 'mojombo',
  'id': 1,
  'node_id': 'MDQ6VXNlcjE=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/1?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/mojombo',
  'html_url': 'https://github.com/mojombo',
  'followers_url': 'https://api.github.com/users/mojombo/followers',
  'following_url': 'https://api.github.com/users/mojombo/following{/other_user}',
  'gists_url': 'https://api.github.com/users/mojombo/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/mojombo/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/mojombo/subscriptions',
  'organizations_url': 'https://api.github.com/users/mojombo/orgs',
  'repos_url': 'https://api.github.com/users/mojombo/repos',
  'events_url': 'https://api.github.com/users/mojombo/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/mojombo/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'defunkt',
  'id': 2,
  'node_id': 'MDQ6VXNlcjI=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/2?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/defunkt',
  'html_url': 'https://github.com/defunkt',
  'followers_url': 'https://api.github.com/users/defunkt/followers',
  'following_url': 'https://api.github.com/users/defunkt/following{/other_user}',
  'gists_url': 'https://api.github.com/users/defunkt/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/defunkt/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/defunkt/subscriptions',
  'organizations_url': 'https://api.github.com/users/defunkt/orgs',
  'repos_url': 'https://api.github.com/users/defunkt/repos',
  'events_url': 'https://api.github.com/users/defunkt/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/defunkt/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'pjhyett',
  'id': 3,
  'node_id': 'MDQ6VXNlcjM=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/3?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/pjhyett',
  'html_url': 'https://github.com/pjhyett',
  'followers_url': 'https://api.github.com/users/pjhyett/followers',
  'following_url': 'https://api.github.com/users/pjhyett/following{/other_user}',
  'gists_url': 'https://api.github.com/users/pjhyett/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/pjhyett/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/pjhyett/subscriptions',
  'organizations_url': 'https://api.github.com/users/pjhyett/orgs',
  'repos_url': 'https://api.github.com/users/pjhyett/repos',
  'events_url': 'https://api.github.com/users/pjhyett/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/pjhyett/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'wycats',
  'id': 4,
  'node_id': 'MDQ6VXNlcjQ=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/4?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/wycats',
  'html_url': 'https://github.com/wycats',
  'followers_url': 'https://api.github.com/users/wycats/followers',
  'following_url': 'https://api.github.com/users/wycats/following{/other_user}',
  'gists_url': 'https://api.github.com/users/wycats/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/wycats/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/wycats/subscriptions',
  'organizations_url': 'https://api.github.com/users/wycats/orgs',
  'repos_url': 'https://api.github.com/users/wycats/repos',
  'events_url': 'https://api.github.com/users/wycats/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/wycats/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'ezmobius',
  'id': 5,
  'node_id': 'MDQ6VXNlcjU=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/5?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/ezmobius',
  'html_url': 'https://github.com/ezmobius',
  'followers_url': 'https://api.github.com/users/ezmobius/followers',
  'following_url': 'https://api.github.com/users/ezmobius/following{/other_user}',
  'gists_url': 'https://api.github.com/users/ezmobius/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/ezmobius/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/ezmobius/subscriptions',
  'organizations_url': 'https://api.github.com/users/ezmobius/orgs',
  'repos_url': 'https://api.github.com/users/ezmobius/repos',
  'events_url': 'https://api.github.com/users/ezmobius/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/ezmobius/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'ivey',
  'id': 6,
  'node_id': 'MDQ6VXNlcjY=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/6?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/ivey',
  'html_url': 'https://github.com/ivey',
  'followers_url': 'https://api.github.com/users/ivey/followers',
  'following_url': 'https://api.github.com/users/ivey/following{/other_user}',
  'gists_url': 'https://api.github.com/users/ivey/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/ivey/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/ivey/subscriptions',
  'organizations_url': 'https://api.github.com/users/ivey/orgs',
  'repos_url': 'https://api.github.com/users/ivey/repos',
  'events_url': 'https://api.github.com/users/ivey/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/ivey/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'evanphx',
  'id': 7,
  'node_id': 'MDQ6VXNlcjc=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/7?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/evanphx',
  'html_url': 'https://github.com/evanphx',
  'followers_url': 'https://api.github.com/users/evanphx/followers',
  'following_url': 'https://api.github.com/users/evanphx/following{/other_user}',
  'gists_url': 'https://api.github.com/users/evanphx/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/evanphx/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/evanphx/subscriptions',
  'organizations_url': 'https://api.github.com/users/evanphx/orgs',
  'repos_url': 'https://api.github.com/users/evanphx/repos',
  'events_url': 'https://api.github.com/users/evanphx/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/evanphx/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'vanpelt',
  'id': 17,
  'node_id': 'MDQ6VXNlcjE3',
  'avatar_url': 'https://avatars.githubusercontent.com/u/17?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/vanpelt',
  'html_url': 'https://github.com/vanpelt',
  'followers_url': 'https://api.github.com/users/vanpelt/followers',
  'following_url': 'https://api.github.com/users/vanpelt/following{/other_user}',
  'gists_url': 'https://api.github.com/users/vanpelt/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/vanpelt/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/vanpelt/subscriptions',
  'organizations_url': 'https://api.github.com/users/vanpelt/orgs',
  'repos_url': 'https://api.github.com/users/vanpelt/repos',
  'events_url': 'https://api.github.com/users/vanpelt/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/vanpelt/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'wayneeseguin',
  'id': 18,
  'node_id': 'MDQ6VXNlcjE4',
  'avatar_url': 'https://avatars.githubusercontent.com/u/18?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/wayneeseguin',
  'html_url': 'https://github.com/wayneeseguin',
  'followers_url': 'https://api.github.com/users/wayneeseguin/followers',
  'following_url': 'https://api.github.com/users/wayneeseguin/following{/other_user}',
  'gists_url': 'https://api.github.com/users/wayneeseguin/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/wayneeseguin/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/wayneeseguin/subscriptions',
  'organizations_url': 'https://api.github.com/users/wayneeseguin/orgs',
  'repos_url': 'https://api.github.com/users/wayneeseguin/repos',
  'events_url': 'https://api.github.com/users/wayneeseguin/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/wayneeseguin/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'brynary',
  'id': 19,
  'node_id': 'MDQ6VXNlcjE5',
  'avatar_url': 'https://avatars.githubusercontent.com/u/19?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/brynary',
  'html_url': 'https://github.com/brynary',
  'followers_url': 'https://api.github.com/users/brynary/followers',
  'following_url': 'https://api.github.com/users/brynary/following{/other_user}',
  'gists_url': 'https://api.github.com/users/brynary/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/brynary/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/brynary/subscriptions',
  'organizations_url': 'https://api.github.com/users/brynary/orgs',
  'repos_url': 'https://api.github.com/users/brynary/repos',
  'events_url': 'https://api.github.com/users/brynary/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/brynary/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'kevinclark',
  'id': 20,
  'node_id': 'MDQ6VXNlcjIw',
  'avatar_url': 'https://avatars.githubusercontent.com/u/20?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/kevinclark',
  'html_url': 'https://github.com/kevinclark',
  'followers_url': 'https://api.github.com/users/kevinclark/followers',
  'following_url': 'https://api.github.com/users/kevinclark/following{/other_user}',
  'gists_url': 'https://api.github.com/users/kevinclark/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/kevinclark/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/kevinclark/subscriptions',
  'organizations_url': 'https://api.github.com/users/kevinclark/orgs',
  'repos_url': 'https://api.github.com/users/kevinclark/repos',
  'events_url': 'https://api.github.com/users/kevinclark/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/kevinclark/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'technoweenie',
  'id': 21,
  'node_id': 'MDQ6VXNlcjIx',
  'avatar_url': 'https://avatars.githubusercontent.com/u/21?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/technoweenie',
  'html_url': 'https://github.com/technoweenie',
  'followers_url': 'https://api.github.com/users/technoweenie/followers',
  'following_url': 'https://api.github.com/users/technoweenie/following{/other_user}',
  'gists_url': 'https://api.github.com/users/technoweenie/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/technoweenie/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/technoweenie/subscriptions',
  'organizations_url': 'https://api.github.com/users/technoweenie/orgs',
  'repos_url': 'https://api.github.com/users/technoweenie/repos',
  'events_url': 'https://api.github.com/users/technoweenie/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/technoweenie/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'macournoyer',
  'id': 22,
  'node_id': 'MDQ6VXNlcjIy',
  'avatar_url': 'https://avatars.githubusercontent.com/u/22?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/macournoyer',
  'html_url': 'https://github.com/macournoyer',
  'followers_url': 'https://api.github.com/users/macournoyer/followers',
  'following_url': 'https://api.github.com/users/macournoyer/following{/other_user}',
  'gists_url': 'https://api.github.com/users/macournoyer/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/macournoyer/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/macournoyer/subscriptions',
  'organizations_url': 'https://api.github.com/users/macournoyer/orgs',
  'repos_url': 'https://api.github.com/users/macournoyer/repos',
  'events_url': 'https://api.github.com/users/macournoyer/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/macournoyer/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'takeo',
  'id': 23,
  'node_id': 'MDQ6VXNlcjIz',
  'avatar_url': 'https://avatars.githubusercontent.com/u/23?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/takeo',
  'html_url': 'https://github.com/takeo',
  'followers_url': 'https://api.github.com/users/takeo/followers',
  'following_url': 'https://api.github.com/users/takeo/following{/other_user}',
  'gists_url': 'https://api.github.com/users/takeo/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/takeo/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/takeo/subscriptions',
  'organizations_url': 'https://api.github.com/users/takeo/orgs',
  'repos_url': 'https://api.github.com/users/takeo/repos',
  'events_url': 'https://api.github.com/users/takeo/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/takeo/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'caged',
  'id': 25,
  'node_id': 'MDQ6VXNlcjI1',
  'avatar_url': 'https://avatars.githubusercontent.com/u/25?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/caged',
  'html_url': 'https://github.com/caged',
  'followers_url': 'https://api.github.com/users/caged/followers',
  'following_url': 'https://api.github.com/users/caged/following{/other_user}',
  'gists_url': 'https://api.github.com/users/caged/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/caged/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/caged/subscriptions',
  'organizations_url': 'https://api.github.com/users/caged/orgs',
  'repos_url': 'https://api.github.com/users/caged/repos',
  'events_url': 'https://api.github.com/users/caged/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/caged/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'topfunky',
  'id': 26,
  'node_id': 'MDQ6VXNlcjI2',
  'avatar_url': 'https://avatars.githubusercontent.com/u/26?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/topfunky',
  'html_url': 'https://github.com/topfunky',
  'followers_url': 'https://api.github.com/users/topfunky/followers',
  'following_url': 'https://api.github.com/users/topfunky/following{/other_user}',
  'gists_url': 'https://api.github.com/users/topfunky/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/topfunky/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/topfunky/subscriptions',
  'organizations_url': 'https://api.github.com/users/topfunky/orgs',
  'repos_url': 'https://api.github.com/users/topfunky/repos',
  'events_url': 'https://api.github.com/users/topfunky/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/topfunky/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'anotherjesse',
  'id': 27,
  'node_id': 'MDQ6VXNlcjI3',
  'avatar_url': 'https://avatars.githubusercontent.com/u/27?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/anotherjesse',
  'html_url': 'https://github.com/anotherjesse',
  'followers_url': 'https://api.github.com/users/anotherjesse/followers',
  'following_url': 'https://api.github.com/users/anotherjesse/following{/other_user}',
  'gists_url': 'https://api.github.com/users/anotherjesse/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/anotherjesse/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/anotherjesse/subscriptions',
  'organizations_url': 'https://api.github.com/users/anotherjesse/orgs',
  'repos_url': 'https://api.github.com/users/anotherjesse/repos',
  'events_url': 'https://api.github.com/users/anotherjesse/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/anotherjesse/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'roland',
  'id': 28,
  'node_id': 'MDQ6VXNlcjI4',
  'avatar_url': 'https://avatars.githubusercontent.com/u/28?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/roland',
  'html_url': 'https://github.com/roland',
  'followers_url': 'https://api.github.com/users/roland/followers',
  'following_url': 'https://api.github.com/users/roland/following{/other_user}',
  'gists_url': 'https://api.github.com/users/roland/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/roland/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/roland/subscriptions',
  'organizations_url': 'https://api.github.com/users/roland/orgs',
  'repos_url': 'https://api.github.com/users/roland/repos',
  'events_url': 'https://api.github.com/users/roland/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/roland/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'lukas',
  'id': 29,
  'node_id': 'MDQ6VXNlcjI5',
  'avatar_url': 'https://avatars.githubusercontent.com/u/29?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/lukas',
  'html_url': 'https://github.com/lukas',
  'followers_url': 'https://api.github.com/users/lukas/followers',
  'following_url': 'https://api.github.com/users/lukas/following{/other_user}',
  'gists_url': 'https://api.github.com/users/lukas/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/lukas/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/lukas/subscriptions',
  'organizations_url': 'https://api.github.com/users/lukas/orgs',
  'repos_url': 'https://api.github.com/users/lukas/repos',
  'events_url': 'https://api.github.com/users/lukas/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/lukas/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'fanvsfan',
  'id': 30,
  'node_id': 'MDQ6VXNlcjMw',
  'avatar_url': 'https://avatars.githubusercontent.com/u/30?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/fanvsfan',
  'html_url': 'https://github.com/fanvsfan',
  'followers_url': 'https://api.github.com/users/fanvsfan/followers',
  'following_url': 'https://api.github.com/users/fanvsfan/following{/other_user}',
  'gists_url': 'https://api.github.com/users/fanvsfan/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/fanvsfan/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/fanvsfan/subscriptions',
  'organizations_url': 'https://api.github.com/users/fanvsfan/orgs',
  'repos_url': 'https://api.github.com/users/fanvsfan/repos',
  'events_url': 'https://api.github.com/users/fanvsfan/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/fanvsfan/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 {'login': 'tomtt',
  'id': 31,
  'node_id': 'MDQ6VXNlcjMx',
  'avatar_url': 'https://avatars.githubusercontent.com/u/31?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/tomtt',
  'html_url': 'https://github.com/tomtt',
  'followers_url': 'https://api.github.com/users/tomtt/followers',

In [56]:
len(df6)

30

In [59]:
for i in range(len(df6)):
    print(df6[i]['url'])

https://api.github.com/users/mojombo
https://api.github.com/users/defunkt
https://api.github.com/users/pjhyett
https://api.github.com/users/wycats
https://api.github.com/users/ezmobius
https://api.github.com/users/ivey
https://api.github.com/users/evanphx
https://api.github.com/users/vanpelt
https://api.github.com/users/wayneeseguin
https://api.github.com/users/brynary
https://api.github.com/users/kevinclark
https://api.github.com/users/technoweenie
https://api.github.com/users/macournoyer
https://api.github.com/users/takeo
https://api.github.com/users/caged
https://api.github.com/users/topfunky
https://api.github.com/users/anotherjesse
https://api.github.com/users/roland
https://api.github.com/users/lukas
https://api.github.com/users/fanvsfan
https://api.github.com/users/tomtt
https://api.github.com/users/railsjitsu
https://api.github.com/users/nitay
https://api.github.com/users/kevwil
https://api.github.com/users/KirinDave
https://api.github.com/users/jamesgolick
https://api.github.com/users/atmos
https://api.github.com/users/sethfitz
https://api.github.com/users/bmizerany
https://api.github.com/users/jnewland