In [3]:
# solving the dataset
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv')

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [5]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [ ]:
df.describe() # statistical information about numerical column

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [11]:
df[['PassengerId','Survived','Pclass']]

     PassengerId  Survived  Pclass
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

[891 rows x 3 columns]

In [6]:
df.dtypes == 'object' # object is string data type

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin          False
Embarked       False
dtype: bool

In [15]:
df.dtypes[df.dtypes == 'object']

Series([], dtype: object)

In [16]:
df.dtypes[df.dtypes == 'object'].index

Index([], dtype='str')

In [17]:
df[df.dtypes[df.dtypes == 'object'].index]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[891 rows x 0 columns]

In [ ]:
df[df.dtypes[df.dtypes != 'object'].index]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df[df.dtypes[df.dtypes != 'object'].index].describe() # describe always give numerical value

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [20]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [21]:
df.describe(include = 'object')

/var/folders/br/l24p9wqx0ml2rhgy4bgyvl9w0000gn/T/ipykernel_26782/1466716981.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = 'object')

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

In [7]:
df.describe(include = 'all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [ ]:
df.describe() # five point summary

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [24]:
df.astype('object').describe()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891,891,891,891,891,714.0,891,891,891,891.00,204,889
unique,891,2,3,891,2,88.0,7,7,681,248.00,147,3
top,1,0,3,"Braund, Mr. Owen Harris",male,24.0,0,0,347082,8.05,G6,S
freq,1,549,491,1,577,30.0,608,678,7,43.00,4,644

In [8]:
df[0:100:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
10,11,1,3,"Sandstrom, Miss Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
50,51,0,3,"Panula, Master Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,NaN,C
65,66,1,3,"Moubarek, Master Gerios",male,NaN,1,1,2661,15.2458,NaN,C
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.0,0,0,C.A. 33111,10.5000,NaN,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S
80,81,0,3,"Waelens, Mr. Achille",male,22.0,0,0,345767,9.0000,NaN,S
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.0,3,0,3101278,15.8500,NaN,S
90,91,0,3,"Christmann, Mr. Emil",male,29.0,0,0,343276,8.0500,NaN,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S

In [9]:
df['new_col'] = 'DS'

In [31]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,DS
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,DS
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,DS
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,DS
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,DS
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,DS
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,DS
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,DS
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,DS
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,DS

In [10]:
df['family'] = df['SibSp'] + df['Parch']

In [33]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,DS,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,DS,1
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,DS,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,DS,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,DS,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,DS,0
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,DS,0
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,DS,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,DS,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,DS,0

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
 12  new_col      891 non-null    str
 13  family       891 non-null    int64
dtypes: float64(2), int64(6), str(6)
memory usage: 97.6 KB

In [12]:
pd.Categorical(df['Pclass']) # different categories of class

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [13]:
pd.Categorical(df['Cabin'])

[NaN, 'C85', NaN, 'C123', NaN, ..., NaN, 'B42', NaN, 'C148', NaN]
Length: 891
Categories (147, str): ['A10', 'A14', 'A16', 'A19', ..., 'F38', 'F4', 'G6', 'T']

In [14]:
df['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: str

In [16]:
df['Cabin'].unique()

<StringArray>
[          nan,         'C85',        'C123',         'E46',          'G6',
        'C103',         'D56',          'A6', 'C23 C25 C27',         'B78',
 ...
        'B102',         'B69',         'E49',         'C47',         'D28',
         'E17',         'A24',         'C50',         'B42',        'C148']
Length: 148, dtype: str

In [39]:
df['Cabin'].nunique()

147

In [17]:
df['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: str

In [18]:
df['Cabin'].value_counts()

Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F33            3
E101           3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 147, dtype: int64

In [23]:
#Q. How many passenger are less that 5 year old
df['Age'] < 5

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [24]:
df[df['Age'] < 5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S,DS,4
10,11,1,3,"Sandstrom, Miss Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S,DS,2
16,17,0,3,"Rice, Master Eugene",male,2.00,4,1,382652,29.1250,NaN,Q,DS,5
43,44,1,2,"Laroche, Miss Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C,DS,3
63,64,0,3,"Skoog, Master Harald",male,4.00,3,2,347088,27.9000,NaN,S,DS,5
78,79,1,2,"Caldwell, Master Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S,DS,2
119,120,0,3,"Andersson, Miss Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S,DS,6
164,165,0,3,"Panula, Master Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,DS,5
171,172,0,3,"Rice, Master Arthur",male,4.00,4,1,382652,29.1250,NaN,Q,DS,5
172,173,1,3,"Johnson, Miss Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S,DS,2
183,184,1,2,"Becker, Master Richard F",male,1.00,2,1,230136,39.0000,F4,S,DS,3
184,185,1,3,"Kink-Heilmann, Miss Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S,DS,2
193,194,1,2,"Navratil, Master Michel M",male,3.00,1,1,230080,26.0000,F2,S,DS,2
205,206,0,3,"Strom, Miss Telma Matilda",female,2.00,0,1,347054,10.4625,G6,S,DS,1
261,262,1,3,"Asplund, Master Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S,DS,6
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,DS,3
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,DS,3
340,341,1,2,"Navratil, Master Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S,DS,2
348,349,1,3,"Coutts, Master William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S,DS,2
374,375,0,3,"Palsson, Miss Stina Viola",female,3.00,3,1,349909,21.0750,NaN,S,DS,4
381,382,1,3,"Nakid, Miss Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C,DS,2
386,387,0,3,"Goodwin, Master Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,DS,7
407,408,1,2,"Richards, Master William Rowe",male,3.00,1,1,29106,18.7500,NaN,S,DS,2
445,446,1,1,"Dodge, Master Washington",male,4.00,0,2,33638,81.8583,A34,S,DS,2
469,470,1,3,"Baclini, Miss Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C,DS,3
479,480,1,3,"Hirvonen, Miss Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S,DS,1
530,531,1,2,"Quick, Miss Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S,DS,2
618,619,1,2,"Becker, Miss Marion Louise",female,4.00,2,1,230136,39.0000,F4,S,DS,3
642,643,0,3,"Skoog, Miss Margit Elizabeth",female,2.00,3,2,347088,27.9000,NaN,S,DS,5
644,645,1,3,"Baclini, Miss Eugenie",female,0.75,2,1,2666,19.2583,NaN,C,DS,3
691,692,1,3,"Karun, Miss Manca",female,4.00,0,1,349256,13.4167,NaN,C,DS,1
750,751,1,2,"Wells, Miss Joan",female,4.00,1,1,29103,23.0000,NaN,S,DS,2
755,756,1,2,"Hamalainen, Master Viljo",male,0.67,1,1,250649,14.5000,NaN,S,DS,2
788,789,1,3,"Dean, Master Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S,DS,3
803,804,1,3,"Thomas, Master Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,DS,1
824,825,0,3,"Panula, Master Urho Abraham",male,2.00,4,1,3101295,39.6875,NaN,S,DS,5
827,828,1,2,"Mallet, Master Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C,DS,2
831,832,1,2,"Richards, Master George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,DS,2
850,851,0,3,"Andersson, Master Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S,DS,6
869,870,1,3,"Johnson, Master Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S,DS,2

In [25]:
len(df[df['Age'] < 5])

40

In [26]:
df[df['Age'] < 5].Name

7                Palsson, Master Gosta Leonard
10              Sandstrom, Miss Marguerite Rut
16                         Rice, Master Eugene
43     Laroche, Miss Simonne Marie Anne Andree
63                        Skoog, Master Harald
78                Caldwell, Master Alden Gates
119           Andersson, Miss Ellis Anna Maria
164                Panula, Master Eino Viljami
171                        Rice, Master Arthur
172                Johnson, Miss Eleanor Ileen
183                   Becker, Master Richard F
184         Kink-Heilmann, Miss Luise Gretchen
193                  Navratil, Master Michel M
205                  Strom, Miss Telma Matilda
261           Asplund, Master Edvin Rojj Felix
297                Allison, Miss Helen Loraine
305              Allison, Master Hudson Trevor
340              Navratil, Master Edmond Roger
348      Coutts, Master William Loch "William"
374                  Palsson, Miss Stina Viola
381                 Nakid, Miss Maria ("Mary")
386             Goodwin, Master Sidney Leonard
407              Richards, Master William Rowe
445                   Dodge, Master Washington
469               Baclini, Miss Helene Barbara
479                    Hirvonen, Miss Hildur E
530                    Quick, Miss Phyllis May
618                 Becker, Miss Marion Louise
642               Skoog, Miss Margit Elizabeth
644                      Baclini, Miss Eugenie
691                          Karun, Miss Manca
750                           Wells, Miss Joan
755                   Hamalainen, Master Viljo
788                  Dean, Master Bertram Vere
803             Thomas, Master Assad Alexander
824                Panula, Master Urho Abraham
827                       Mallet, Master Andre
831             Richards, Master George Sibley
850     Andersson, Master Sigvard Harald Elias
869             Johnson, Master Harold Theodor
Name: Name, dtype: str

In [27]:
list(df[df['Age'] < 5].Name)

['Palsson, Master Gosta Leonard',
 'Sandstrom, Miss Marguerite Rut',
 'Rice, Master Eugene',
 'Laroche, Miss Simonne Marie Anne Andree',
 'Skoog, Master Harald',
 'Caldwell, Master Alden Gates',
 'Andersson, Miss Ellis Anna Maria',
 'Panula, Master Eino Viljami',
 'Rice, Master Arthur',
 'Johnson, Miss Eleanor Ileen',
 'Becker, Master Richard F',
 'Kink-Heilmann, Miss Luise Gretchen',
 'Navratil, Master Michel M',
 'Strom, Miss Telma Matilda',
 'Asplund, Master Edvin Rojj Felix',
 'Allison, Miss Helen Loraine',
 'Allison, Master Hudson Trevor',
 'Navratil, Master Edmond Roger',
 'Coutts, Master William Loch "William"',
 'Palsson, Miss Stina Viola',
 'Nakid, Miss Maria ("Mary")',
 'Goodwin, Master Sidney Leonard',
 'Richards, Master William Rowe',
 'Dodge, Master Washington',
 'Baclini, Miss Helene Barbara',
 'Hirvonen, Miss Hildur E',
 'Quick, Miss Phyllis May',
 'Becker, Miss Marion Louise',
 'Skoog, Miss Margit Elizabeth',
 'Baclini, Miss Eugenie',
 'Karun, Miss Manca',
 'Wells, Miss Joan',
 'Hamalainen, Master Viljo',
 'Dean, Master Bertram Vere',
 'Thomas, Master Assad Alexander',
 'Panula, Master Urho Abraham',
 'Mallet, Master Andre',
 'Richards, Master George Sibley',
 'Andersson, Master Sigvard Harald Elias',
 'Johnson, Master Harold Theodor']

In [34]:
# hjow many person are less than 18 year old

list(df[df['Age'] > 18].Name)

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'McCarthy, Mr. Timothy J',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
 'Bonnell, Miss Elizabeth',
 'Saundercock, Mr. William Henry',
 'Andersson, Mr. Anders Johan',
 'Hewlett, Mrs. (Mary D Kingcome) ',
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
 'Fynney, Mr. Joseph J',
 'Beesley, Mr. Lawrence',
 'Sloper, Mr. William Thompson',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Fortune, Mr. Charles Alexander',
 'Uruchurtu, Don. Manuel E',
 'Wheadon, Mr. Edward H',
 'Meyer, Mr. Edgar Joseph',
 'Holverson, Mr. Alexander Oskar',
 'Cann, Mr. Ernest Charles',
 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
 'Devaney, Miss Margaret Delia',
 'Nosworthy, Mr. Richard Cater',
 'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
 'Ostby, Mr. Engelhart Cornelius',
 'Rugg, Miss Emily',
 'Novel, Mr. Mansouer',
 'Sirayanian, Mr. Orsen',
 'Icard, Miss Amelie',
 'Harris, Mr. Henry Birkhardt',
 'Nye, Mrs. (Elizabeth Ramell)',
 'Crease, Mr. Ernest James',
 'Kink, Mr. Vincenz',
 'Jenkin, Mr. Stephen Curnow',
 'Hood, Mr. Ambrose Jr',
 'Chronopoulos, Mr. Apostolos',
 'Bing, Mr. Lee',
 'Moen, Mr. Sigurd Hansen',
 'Dowdell, Miss Elizabeth',
 'Waelens, Mr. Achille',
 'Sheerlinck, Mr. Jan Baptist',
 'Carrau, Mr. Francisco M',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Fortune, Miss Mabel Helen',
 'Celotti, Mr. Francesco',
 'Christmann, Mr. Emil',
 'Andreasson, Mr. Paul Edvin',
 'Chaffee, Mr. Herbert Fuller',
 'Dean, Mr. Bertram Frank',
 'Coxon, Mr. Daniel',
 'Goldschmidt, Mr. George B',
 'Greenfield, Mr. William Bertram',
 'Doling, Mrs. John T (Ada Julia Bone)',
 'Kantor, Mr. Sinai',
 'Petranec, Miss Matilda',
 'White, Mr. Richard Frasar',
 'Johansson, Mr. Gustaf Joel',
 'Gustafsson, Mr. Anders Vilhelm',
 'Mionoff, Mr. Stoytcho',
 'Salkjelsvik, Miss Anna Kristine',
 'Rekic, Mr. Tido',
 'Porter, Mr. Walter Chamberlain',
 'Barton, Mr. David John',
 'Jussila, Miss Katriina',
 'Pekoniemi, Mr. Edvard',
 'Connors, Mr. Patrick',
 'Turpin, Mr. William John Robert',
 'Baxter, Mr. Quigg Edmond',
 'Hickman, Mr. Stanley George',
 'Nasser, Mr. Nicholas',
 'Webber, Miss Susan',
 'White, Mr. Percival Wayland',
 'Madsen, Mr. Fridtjof Arne',
 'Ekstrom, Mr. Johan',
 'Drazenoic, Mr. Jozef',
 'Coelho, Mr. Domingos Fernandeo',
 'Robins, Mrs. Alexander A (Grace Charity Laury)',
 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
 'Sobey, Mr. Samuel James Hayden',
 'Richard, Mr. Emile',
 'Newsom, Miss Helen Monypeny',
 'Futrelle, Mr. Jacques Heath',
 'Giglio, Mr. Victor',
 'Nysten, Miss Anna Sofia',
 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
 'Burke, Mr. Jeremiah',
 'Nicholls, Mr. Joseph Charles',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Navratil, Mr. Michel ("Louis M Hoffman")',
 'Byles, Rev. Thomas Roussel Davids',
 'Bateman, Rev. Robert James',
 'Pears, Mrs. Thomas (Edith Wearne)',
 'Meo, Mr. Alfonzo',
 'van Billiard, Mr. Austin Blyler',
 'Williams, Mr. Charles Duane',
 'Corn, Mr. Harry',
 'Cribb, Mr. John Hatfield',
 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
 'Bengtsson, Mr. John Viktor',
 'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
 'Ling, Mr. Lee',
 'Van der hoef, Mr. Wyckoff',
 'Sivola, Mr. Antti Wilhelm',
 'Smith, Mr. James Clinch',
 'Isham, Miss Ann Elizabeth',
 'Hale, Mr. Reginald',
 'Leonard, Mr. Lionel',
 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")',
 'Bourke, Mr. John',
 'Turcin, Mr. Stjepan',
 'Pinsky, Mrs. (Rosa)',
 'Carbines, Mr. William',
 'Andersen-Jensen, Miss Carla Christine Nielsine',
 'Brown, Mrs. James Joseph (Margaret Tobin)',
 'Lurette, Miss Elise',
 'Olsen, Mr. Karl Siegwart Andreas',
 'Yrois, Miss Henriette ("Mrs Harbeck")',
 'Vande Walle, Mr. Nestor Cyriel',
 'Johanson, Mr. Jakob Alfred',
 'Youseff, Mr. Gerious',
 'Backstrom, Mr. Karl Alfred',
 'Albimona, Mr. Nassef Cassem',
 'Blank, Mr. Henry',
 'Ali, Mr. Ahmed',
 'Cameron, Miss Clear Annie',
 'Perkin, Mr. John Henry',
 'Givard, Mr. Hans Kristensen',
 'Newell, Miss Madeleine',
 'Honkanen, Miss Eliina',
 'Jacobsohn, Mr. Sidney Samuel',
 'Bazzani, Miss Albina',
 'Harris, Mr. Walter',
 'Bracken, Mr. James H',
 'Green, Mr. George Henry',
 'Hoyt, Mr. Frederick Maxfield',
 'Berglund, Mr. Karl Ivar Sven',
 'Mellors, Mr. William John',
 'Lovell, Mr. John Hall ("Henry")',
 'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
 'Larsson, Mr. Bengt Edvin',
 'Sjostedt, Mr. Ernst Adolf',
 'Leyson, Mr. Robert William Norman',
 'Hold, Mr. Stephen',
 'Pengelly, Mr. Frederick William',
 'Hunt, Mr. George Henry',
 'Coleridge, Mr. Reginald Charles',
 'Maenpaa, Mr. Matti Alexanteri',
 'Attalah, Mr. Sleiman',
 'Minahan, Dr. William Edward',
 'Lindahl, Miss Agda Thorilda Viktoria',
 'Hamalainen, Mrs. William (Anna)',
 'Beckwith, Mr. Richard Leonard',
 'Carter, Rev. Ernest Courtenay',
 'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
 'Stead, Mr. William Thomas',
 'Lobb, Mr. William Arthur',
 'Rosblom, Mrs. Viktor (Helena Wilhelmina)',
 'Touma, Mrs. Darwis (Hanne Youssef Razi)',
 'Cherry, Miss Gladys',
 'Ward, Miss Anna',
 'Parrish, Mrs. (Lutie Davis)',
 'Taussig, Mr. Emil',
 'Harrison, Mr. William',
 'Reeves, Mr. David',
 'Persson, Mr. Ernst Ulrik',
 'Graham, Mrs. William Thompson (Edith Junkins)',
 'Bissette, Miss Amelia',
 'Tornquist, Mr. William Henry',
 'Mellinger, Mrs. (Elizabeth Anne Maidment)',
 'Natsch, Mr. Charles H',
 'Andrews, Miss Kornelia Theodosia',
 'Lindblom, Miss Augusta Charlotta',
 'Abbott, Mrs. Stanton (Rosa Hunt)',
 'Duane, Mr. Frank',
 'Olsson, Mr. Nils Johan Goransson',
 'Dorking, Mr. Edward Arthur',
 'Stankovic, Mr. Ivan',
 'de Mulder, Mr. Theodore',
 'Naidenoff, Mr. Penko',
 'Hosono, Mr. Masabumi',
 'Connolly, Miss Kate',
 'Barber, Miss Ellen "Nellie"',
 'Bishop, Mrs. Dickinson H (Helen Walton)',
 'Levy, Mr. Rene Jacques',
 'Haas, Miss Aloisia',
 'Mineff, Mr. Ivan',
 'Hanna, Mr. Mansour',
 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
 'Johnson, Mr. William Cahoone Jr',
 'Abelson, Mr. Samuel',
 'Francatelli, Miss Laura Mabel',
 'Hays, Miss Margaret Bechstein',
 'Lahtinen, Mrs. William (Anna Sylfven)',
 'Hendekovic, Mr. Ignjac',
 'Hart, Mr. Benjamin',
 'Nilsson, Miss Helmina Josefina',
 'Kantor, Mrs. Sinai (Miriam Sternin)',
 'Moraweck, Dr. Ernest',
 'Wick, Miss Mary Natalie',
 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
 'Dennis, Mr. Samuel',
 'Danoff, Mr. Yoto',
 'Slayter, Miss Hilda Mary',
 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
 'Young, Miss Marie Grice',
 'Nysveen, Mr. Johan Hansen',
 'Ball, Mrs. (Ada E Hall)',
 'Goldsmith, Mrs. Frank John (Emily Alice Brown)',
 'Partner, Mr. Austen',
 'Graham, Mr. George Edward',
 'Pears, Mr. Thomas Clinton',
 'Burns, Miss Elizabeth Margaret',
 'Dahl, Mr. Karl Edwart',
 'Blackwell, Mr. Stephen Weart',
 'Fortune, Miss Alice Elizabeth',
 'Collander, Mr. Erik Gustaf',
 'Sedgwick, Mr. Charles Frederick Waddington',
 'Fox, Mr. Stanley Hubert',
 'Brown, Miss Amelia "Mildred"',
 'Smith, Miss Marion Elsie',
 'Dimic, Mr. Jovan',
 'Odahl, Mr. Nils Martin',
 'Arnold-Franchi, Mr. Josef',
 'Vanden Steen, Mr. Leo Peter',
 'Bowerman, Miss Elsie Edith',
 'Funk, Miss Annie Clemmer',
 'Skoog, Mr. Wilhelm',
 'del Carlo, Mr. Sebastiano',
 'Barbara, Mrs. (Catherine David)',
 'Asim, Mr. Adola',
 'Adahl, Mr. Mauritz Nils Martin',
 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
 'Aubart, Mme. Leontine Pauline',
 'Harder, Mr. George Achilles',
 'Beavan, Mr. William Thomas',
 'Ringhini, Mr. Sante',
 'Landergren, Miss Aurora Adelia',
 'Widener, Mr. Harry Elkins',
 'Betros, Mr. Tannous',
 'Gustafsson, Mr. Karl Gideon',
 'Bidois, Miss Rosalie',
 'Tikkanen, Mr. Juho',
 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
 'Buss, Miss Kate',
 'Carter, Mr. William Ernest',
 'Jansson, Mr. Carl Olof',
 'Gustafsson, Mr. Johan Birger',
 'Newell, Miss Marjorie',
 'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
 'Johansson, Mr. Erik',
 'Olsson, Miss Elina',
 'McKane, Mr. Peter David',
 'Pain, Dr. Alfred',
 'Trout, Mrs. William H (Jessie L)',
 'Niskanen, Mr. Juha',
 'Adams, Mr. John',
 'Jussila, Miss Mari Aina',
 'Hakkarainen, Mr. Pekka Pietari',
 'Oreskovic, Miss Marija',
 'Gale, Mr. Shadrach',
 'Widegren, Mr. Carl/Charles Peter',
 'Birkeland, Mr. Hans Martin Monsen',
 'Minahan, Miss Daisy E',
 'Sundman, Mr. Johan Julian',
 'Drew, Mrs. James Vivian (Lulu Thorne Christian)',
 'Matthews, Mr. William John',
 'Charters, Mr. David',
 'Zimmerman, Mr. Leo',
 'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
 'Clarke, Mrs. Charles V (Ada Maria Winfield)',
 'Phillips, Miss Kate Florence ("Mrs Kate Louise Phillips Marshall")',
 'Pickard, Mr. Berk (Berk Trembisky)',
 'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
 'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
 'Silvey, Mr. William Baird',
 'Ford, Miss Doolina Margaret "Daisy"',
 'Richards, Mrs. Sidney (Emily Hocking)',
 'Fortune, Mr. Mark',
 'Kvillner, Mr. Johan Henrik Johannesson',
 'Hart, Mrs. Benjamin (Esther Ada Bloomfield)',
 'Hampe, Mr. Leon',
 'Petterson, Mr. Johan Emil',
 'Reynaldo, Ms. Encarnacion',
 'Seward, Mr. Frederic Kimber',
 'Peuchen, Major. Arthur Godfrey',
 'West, Mr. Edwy Arthur',
 'Foreman, Mr. Benjamin Laventall',
 'Goldenberg, Mr. Samuel L',
 'Jalsevac, Mr. Ivan',
 'Millet, Mr. Francis Davis',
 'Toomey, Miss Ellen',
 'Anderson, Mr. Harry',
 'Morley, Mr. William',
 'Gee, Mr. Arthur H',
 'Milling, Mr. Jacob Christian',
 'Goncalves, Mr. Manuel Estanslas',
 'Smart, Mr. John Montgomery',
 'Cacic, Mr. Luka',
 'West, Mrs. Edwy Arthur (Ada Mary Worth)',
 'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
 'Strandberg, Miss Ida Sofia',
 'Renouf, Mr. Peter Henry',
 'Braund, Mr. Lewis Richard',
 'Karlsson, Mr. Nils August',
 'Rouse, Mr. Richard Henry',
 'Turkula, Mrs. (Hedwig)',
 'Bishop, Mr. Dickinson H',
 'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
 'Kent, Mr. Edward Austin',
 'Somerton, Mr. Francis William',
 'Windelov, Mr. Einar',
 'Molson, Mr. Harry Markland',
 'Artagaveytia, Mr. Ramon',
 'Stanley, Mr. Edward Roland',
 'Eustis, Miss Elizabeth Mussey',
 'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
 'Svensson, Mr. Olof',
 'Canavan, Miss Mary',
 'Laitinen, Miss Kristina Sofia',
 'Quick, Mrs. Frederick Charles (Jane Richards)',
 'Olsen, Mr. Henry Margido',
 'Lang, Mr. Fang',
 'Daly, Mr. Eugene Patrick',
 'McGough, Mr. James Robert',
 'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
 'Coleff, Mr. Satio',
 'Walker, Mr. William Anderson',
 'Lemore, Mrs. (Amelia Milley)',
 'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
 'Pavlovic, Mr. Stefo',
 'Perreault, Miss Anne',
 'Vovk, Mr. Janko',
 'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
 'Farrell, Mr. James',
 'Ridsdale, Miss Lucy',
 'Salonen, Mr. Johan Werner',
 'Hocking, Mr. Richard George',
 'Cacic, Miss Marija',
 'Butt, Major. Archibald Willingham',
 'LeRoy, Miss Bertha',
 'Frolicher, Miss Hedwig Margaritha',
 'Crosby, Miss Harriet R',
 'Beane, Mr. Edward',
 'Douglas, Mr. Walter Donald',
 'Nicholson, Mr. Arthur Ernest',
 'Beane, Mrs. Edward (Ethel Clarke)',
 'Goldsmith, Mr. Frank John',
 'Sharp, Mr. Percival James R',
 'Leeni, Mr. Fahim ("Philip Zenni")',
 'Ohman, Miss Velin',
 'Wright, Mr. George',
 'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
 'Taussig, Mrs. Emil (Tillie Mandelbaum)',
 'de Messemaeker, Mrs. Guillaume Joseph (Emma)',
 'Sivic, Mr. Husein',
 'Norman, Mr. Robert Douglas',
 'Davies, Mr. Alfred J',
 'Stoytcheff, Mr. Ilia',
 'Palsson, Mrs. Nils (Alma Cornelia Berglund)',
 'Jonsson, Mr. Carl',
 'Harris, Mr. George',
 'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
 'Flynn, Mr. John Irwin ("Irving")',
 'Patchett, Mr. George',
 'Garside, Miss Ethel',
 'Silvey, Mrs. William Baird (Alice Munger)',
 'Jussila, Mr. Eiriik',
 'Christy, Miss Julie Rachel',
 'Thayer, Mrs. John Borland (Marian Longstreth Morris)',
 'Downton, Mr. William James',
 'Ross, Mr. John Hugo',
 'Jarvis, Mr. John Denzil',
 'Frolicher-Stehli, Mr. Maxmillian',
 'Gilinski, Mr. Eliezer',
 'Rintamaki, Mr. Matti',
 'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
 'Elsbury, Mr. William James',
 'Chapman, Mr. John Henry',
 'Van Impe, Mr. Jean Baptiste',
 'Johnson, Mr. Alfred',
 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")',
 'Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)',
 'Torber, Mr. Ernst William',
 'Homer, Mr. Harry ("Mr E Haven")',
 'Lindell, Mr. Edvard Bengtsson',
 'Karaic, Mr. Milan',
 'Daniel, Mr. Robert Williams',
 'Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)',
 'Shutes, Miss Elizabeth W',
 'Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)',
 'Brocklebank, Mr. William Alfred',
 'Herman, Miss Alice',
 'Danbom, Mr. Ernst Gilbert',
 'Lobb, Mrs. William Arthur (Cordelia K Stanlick)',
 'Gavey, Mr. Lawrence',
 'Yasbeck, Mr. Antoni',
 'Kimball, Mr. Edwin Nelson Jr',
 'Nakid, Mr. Sahid',
 'Hansen, Mr. Henry Damsgaard',
 'Bowen, Mr. David John "Dai"',
 'Sutton, Mr. Frederick',
 'Kirkland, Rev. Charles Leonard',
 'Longley, Miss Gretchen Fiske',
 'Bostandyeff, Mr. Guentcho',
 'Barkworth, Mr. Algernon Henry Wilson',
 'Lundahl, Mr. Johan Svensson',
 'Stahelin-Maeglin, Dr. Max',
 'Davis, Miss Mary',
 'Leinonen, Mr. Antti Gustaf',
 'Collyer, Mr. Harvey',
 'Panula, Mrs. Juha (Maria Emilia Ojala)',
 'Jensen, Mr. Hans Peder',
 'Sagesser, Mlle. Emma',
 'Harper, Mr. Henry Sleeper',
 'Cor, Mr. Liudevit',
 'Simonius-Blumer, Col. Oberst Alfons',
 'Stanley, Miss Amy Zillah Elsie',
 'Kalvik, Mr. Johannes Halvorsen',
 'Hickman, Mr. Leonard Mark',
 'Bourke, Mrs. John (Catherine)',
 'Eitemiller, Mr. George Floyd',
 'Newell, Mr. Arthur Webster',
 'Frauenthal, Dr. Henry William',
 'Badt, Mr. Mohamed',
 'Colley, Mr. Edward Pomeroy',
 'Coleff, Mr. Peju',
 'Lindqvist, Mr. Eino William',
 'Hickman, Mr. Lewis',
 'Butler, Mr. Reginald Fenton',
 'Cook, Mr. Jacob',
 'Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)',
 'Davidson, Mr. Thornton',
 'Mitchell, Mr. Henry Michael',
 'Wilhelms, Mr. Charles',
 'Sawyer, Mr. Frederick Charles',
 'Goodwin, Mrs. Frederick (Augusta Tyler)',
 'Cardeza, Mr. Thomas Drake Martinez',
 'Hassab, Mr. Hammad',
 'Olsvigen, Mr. Thor Anderson',
 'Brown, Mr. Thomas William Solomon',
 'Laroche, Mr. Joseph Philippe Lemercier',
 'Dakic, Mr. Branko',
 'Dick, Mr. Albert Adrian',
 'Saad, Mr. Khalil',
 'Weir, Col. John',
 'Chapman, Mr. Charles Henry',
 'Kelly, Mr. James',
 'Thayer, Mr. John Borland',
 'Humblen, Mr. Adolf Mathias Nicolai Olsen',
 'Silverthorne, Mr. Spencer Victor',
 'Gallagher, Mr. Martin',
 'Hansen, Mr. Henrik Juul',
 'Morley, Mr. Henry Samuel ("Mr Henry Marshall")',
 'Kelly, Mrs. Florence "Fannie"',
 'Calderhead, Mr. Edward Pennington',
 'Cleaver, Miss Alice',
 'Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")',
 'Taylor, Mr. Elmer Zebley',
 'Larsson, Mr. August Viktor',
 'Greenberg, Mr. Samuel',
 'Soholt, Mr. Peter Andreas Lauritz Andersen',
 'Endres, Miss Caroline Louise',
 'Troutt, Miss Edwina Celia "Winnie"',
 'Johnson, Mr. Malkolm Joackim',
 'Gillespie, Mr. William Henry',
 'Hodges, Mr. Henry Price',
 'Chambers, Mr. Norman Campbell',
 'Oreskovic, Mr. Luka',
 'Renouf, Mrs. Peter Henry (Lillian Jefferys)',
 'Bryhl, Mr. Kurt Arnold Gottfrid',
 'Ilmakangas, Miss Pieta Sofia',
 'Allen, Miss Elisabeth Walton',
 'Berriman, Mr. William John',
 'Troupiansky, Mr. Moses Aaron',
 'Williams, Mr. Leslie',
 'Ford, Mrs. Edward (Margaret Ann Watson)',
 'Lesurer, Mr. Gustave J',
 'Cavendish, Mr. Tyrell William',
 'Ryerson, Miss Susan Parker "Suzette"',
 'McNamee, Mr. Neal',
 'Stranden, Mr. Juho',
 'Crosby, Capt. Edward Gifford',
 'Sinkkonen, Miss Anna',
 'Marvin, Mr. Daniel Warner',
 'Connaghton, Mr. Michael',
 'Vande Velde, Mr. Johannes Joseph',
 'Jonkoff, Mr. Lalio',
 'Herman, Mrs. Samuel (Jane Laver)',
 'Carlsson, Mr. August Sigfrid',
 'Theobald, Mr. Thomas Leonard',
 'Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)',
 'Nirva, Mr. Iisakki Antino Aijo',
 'Barah, Mr. Hanna Assi',
 'Carter, Mrs. William Ernest (Lucile Polk)',
 'Hogeboom, Mrs. John C (Anna Andrews)',
 'Mangan, Miss Mary',
 'Gronnestad, Mr. Daniel Danielsen',
 'Lievens, Mr. Rene Aime',
 'Jensen, Mr. Niels Peder',
 'Mack, Mrs. (Mary)',
 'Hocking, Mrs. Elizabeth (Eliza Needs)',
 'Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)',
 'Long, Mr. Milton Clyde',
 'Ali, Mr. William',
 'Harmer, Mr. Abraham (David Lishin)',
 'Guggenheim, Mr. Benjamin',
 'Dantcheff, Mr. Ristiu',
 'Otter, Mr. Richard',
 'Leader, Dr. Alice (Farnham)',
 'Osman, Mrs. Mara',
 'Ibrahim Shawah, Mr. Yousseff',
 'Van Impe, Mrs. Jean Baptiste (Rosalie Paula Govaert)',
 'Ponesell, Mr. Martin',
 'Collyer, Mrs. Harvey (Charlotte Annie Tate)',
 'Hedman, Mr. Oskar Arvid',
 'Johansson, Mr. Karl Johan',
 'Andrews, Mr. Thomas Jr',
 'Meyer, Mr. August',
 'Chambers, Mrs. Norman Campbell (Bertha Griggs)',
 'Alexander, Mr. William',
 'Lester, Mr. James',
 'Slemen, Mr. Richard James',
 'Tomlin, Mr. Ernest Portage',
 'Heininen, Miss Wendla Maria',
 'Mallet, Mr. Albert',
 'Holm, Mr. John Fredrik Alexander',
 'Hays, Mrs. Charles Melville (Clara Jennings Gregg)',
 'Lulic, Mr. Nikola',
 'Reuchlin, Jonkheer. John George',
 'Moor, Mrs. (Beila)',
 'Stone, Mrs. George Nelson (Martha Evelyn)',
 'Augustsson, Mr. Albert',
 'Compton, Miss Sara Rebecca',
 'Pasic, Mr. Jakob',
 'Chip, Mr. Chang',
 'Alhomaki, Mr. Ilmari Rudolf',
 'Serepeca, Miss Augusta',
 'Lemberopolous, Mr. Peter L',
 'Abbing, Mr. Anthony',
 'Markoff, Mr. Marin',
 'Harper, Rev. John',
 'Svensson, Mr. Johan',
 'Carter, Mrs. Ernest Courtenay (Lilian Hughes)',
 'Wick, Mrs. George Dennick (Mary Hitchcock)',
 'Daly, Mr. Peter Denis ',
 'Baclini, Mrs. Solomon (Latifa Qurban)',
 'Hansen, Mr. Claus Peter',
 'Giles, Mr. Frederick Edward',
 'Swift, Mrs. Frederick Joel (Margaret Welles Barron)',
 'Gill, Mr. John William',
 'Bystrom, Mrs. (Karolina)',
 'Duran y More, Miss Asuncion',
 'Roebling, Mr. Washington Augustus II',
 'Balkic, Mr. Cerin',
 'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)',
 'Carlsson, Mr. Frans Olof',
 'Vander Cruyssen, Mr. Victor',
 'Abelson, Mrs. Samuel (Hannah Wizosky)',
 'Gustafsson, Mr. Alfred Ossian',
 'Petroff, Mr. Nedelio',
 'Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)',
 'Shelley, Mrs. William (Imanita Parrish Hall)',
 'Markun, Mr. Johann',
 'Dahlberg, Miss Gerda Ulrika',
 'Banfield, Mr. Frederick James',
 'Sutehall, Mr. Henry Jr',
 'Rice, Mrs. William (Margaret Norton)',
 'Montvila, Rev. Juozas',
 'Graham, Miss Margaret Edith',
 'Behr, Mr. Karl Howell',
 'Dooley, Mr. Patrick']

In [35]:
len(list(df[df['Age'] > 18].Name))

575

In [36]:
df['Fare']

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [37]:
df['Fare'].mean()

np.float64(32.204207968574636)

In [39]:
# how many passenger have epaid less than avg fare

df[df['Fare'] < df['Fare'].mean()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,DS,1
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,DS,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,DS,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,DS,0
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,DS,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,DS,0
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,DS,0
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,DS,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,DS,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,DS,0

In [ ]:
df[df['Fare'] < 32] # 32 is average value

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,DS,1
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,DS,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,DS,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,DS,0
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,DS,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,DS,0
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,DS,0
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,DS,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,DS,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,DS,0

In [41]:
len(df[df['Fare'] < df['Fare'].mean()])

680

In [47]:
# How many passenger paid 0 fare

df[df['Fare'] == 0]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0,NaN,S,DS,0
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S,DS,0
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,NaN,S,DS,0
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S,DS,0
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0,NaN,S,DS,0
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0,NaN,S,DS,0
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S,DS,0
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S,DS,0
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0,NaN,S,DS,0
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S,DS,0
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S,DS,0
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S,DS,0
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S,DS,0
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S,DS,0
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S,DS,0

In [45]:
len(df[df['Fare'] == 0])

15

In [49]:
df[df['Sex'] == 'male']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,DS,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,DS,0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,DS,0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,DS,0
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,DS,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,DS,0
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,DS,0
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,DS,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,DS,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,DS,0

In [50]:
len(df[df['Sex'] == 'male'])

577

In [51]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
df['Sex'].value_counts(normalize= True) # normalize show percentage of male and female

Sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

In [54]:
# how many passenger from class 1

df[df['Pclass'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,DS,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,DS,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,DS,0
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,DS,0
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,DS,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,DS,2
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,DS,0
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,DS,1
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,DS,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,DS,0

In [55]:
# how many passenger from survived 1

df[df['Survived'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,DS,1
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,DS,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,DS,1
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,DS,2
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,DS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,DS,0
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,DS,1
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,DS,1
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,DS,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,DS,0

In [57]:
df['Survived'].value_counts(normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [58]:
# How many female more than avg fare

In [60]:
df['Sex'] == 'female'

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [61]:
df['Fare'].mean()

np.float64(32.204207968574636)

In [ ]:
df[(df['Sex'] == 'female') & (df['Fare'] > df['Fare'].mean())]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,DS,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,DS,1
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,DS,1
43,44,1,2,"Laroche, Miss Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,DS,3
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,DS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,854,1,1,"Lines, Miss Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S,DS,1
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,DS,2
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,DS,10
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,DS,2
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,DS,1

In [65]:
len(df[(df['Sex'] == 'female') & (df['Fare'] > df['Fare'].mean())])

104

In [66]:
len(df[(df['Sex'] == 'male') & (df['Fare'] > df['Fare'].mean())])

107

In [67]:
import numpy as np
np.mean(df.Fare)

np.float64(32.204207968574636)

In [70]:
df.Fare.mean()

np.float64(32.204207968574636)

In [71]:
max(df.Fare)

512.3292

In [73]:
min(df['Fare'])

0.0

In [74]:
df[df['Fare'] == max(df.Fare)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
258,259,1,1,"Ward, Miss Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,DS,0
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,DS,1
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,DS,0

In [76]:
df[df['Fare'] == max(df.Fare)].Name

258                       Ward, Miss Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: str

In [78]:
df[(df.Age > 18) & (df['Survived'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,family
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,DS,1
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,DS,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,DS,1
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,DS,2
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,DS,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,DS,1
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,DS,1
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,DS,1
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,DS,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,DS,0

In [80]:
len(df[(df.Age > 18) & (df['Survived'] == 1)])

220